# Generated by Django 5.0.dev20230305130119 on 2023-06-05 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('prezime', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bloker', to='App.avtor')),
                ('blokiran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_blokiran', to='App.avtor')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=50)),
                ('sodrzina', models.TextField(blank=True, null=True)),
                ('datum_created', models.DateField(auto_now_add=True)),
                ('datum_last_modified', models.DateField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('avtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.avtor')),
                ('blocked_users', models.ManyToManyField(blank=True, related_name='blocked_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sodrzina', models.TextField(blank=True, null=True)),
                ('datum_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.avtor')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.post')),
            ],
        ),
    ]
